### ISSUE TITLE
Gazebo plugin or the mathmatical formula of the pattern?

### ISSUE THREAD

**Issue by EpsAvlc** [Livox-SDK/livox_detection_simu#1]
Hi, I am trying to apply Livox Horizon in autonomous exploraion task. However there is neither the gazebo plug-in for Livox horizon nor the principle of the scanning pattern of the horizon. Any ideas? So I may try to implement a gazebo plug-in myself.

**Comment by Livox-SDK** [comment]
Hi, Livox Horizon is currently not supported in Gazebo. The scanning pattern of Livox Horizon may be released later.

**Comment by amrita9suresh** [comment]
Hello, I was wondering if any support for Livox Horizon on Gazebo has been released yet? I am currently working on a perception problem with it and it would really save time if the plugin is readily available.

**Comment by EpsAvlc** [comment]
> Hello, I was wondering if any support for Livox Horizon on Gazebo has been released yet? I am currently working on a perception problem with it and it would really save time if the plugin is readily available.

[livox_laser_simulation](https://github.com/lvfengchi/livox_laser_simulation)which is maintained by Fengchi Lv and me.

**Comment by amrita9suresh** [comment]
> > Hello, I was wondering if any support for Livox Horizon on Gazebo has been released yet? I am currently working on a perception problem with it and it would really save time if the plugin is readily available.
> 
> [livox_laser_simulation](https://github.com/lvfengchi/livox_laser_simulation)which is maintained by Fengchi Lv and me.

Perfect! Thanks a ton!
